### ISSUE TITLE
retrying when NOT_ENOUGH_TOKEN and asin list become empty

### ISSUE THREAD

**Issue by threemonks** [akaszynski/keepa#28]
When I submit a product query with offers=20, to obtain new_fba price etc, it might come back with NOT_ENOUGH_TOKEN exception, but I noticed a few issues with the exception handling and retry. Here is API call with offers=20 to retrieve new_fba price (I passed 20 asins into the API call):

`ProductQuery(asins, offers=20, history=True)`

Here is the log:
`Exception2018-09-15 20:46:47,664 - {C:\Python27\lib\site-packages\keepaAPI\interface.py:57} - WARNING - Exception NOT_ENOUGH_TOKEN in thread.  Waiting 60 seconds for retry.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 54, in ThreadRequest
    response = ProductQuery(asins, settings)
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 255, in ProductQuery
    raise Exception(scodes[str(status_code)])
Exception: NOT_ENOUGH_TOKEN
: Error in thread
2018-09-15 20:46:48,059 - {C:\Python27\lib\site-packages\keepaAPI\interface.py:57} - WARNING - Exception NOT_ENOUGH_TOKEN in thread.  Waiting 60 seconds for retry.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 54, in ThreadRequest
    response = ProductQuery(asins, settings)
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 255, in ProductQuery
    raise Exception(scodes[str(status_code)])
Exception: NOT_ENOUGH_TOKEN
2018-09-15 20:47:47,244 - {C:\Python27\lib\site-packages\keepaAPI\interface.py:57} - WARNING - Exception 'products' in thread.  Waiting 60 seconds for retry.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 54, in ThreadRequest
    response = ProductQuery(asins, settings)
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 247, in ProductQuery
    for product in response['products']:
KeyError: 'products'
2018-09-15 20:47:47,663 - {C:\Python27\lib\site-packages\keepaAPI\interface.py:57} - WARNING - Exception 'products' in thread.  Waiting 60 seconds for retry.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 54, in ThreadRequest
    response = ProductQuery(asins, settings)
  File "C:\Python27\lib\site-packages\keepaAPI\interface.py", line 247, in ProductQuery
    for product in response['products']:
KeyError: 'products'
2018-09-15 20:47:47,678 - {C:\Python27\lib\site-packages\keepaAPI\interface.py:65} - ERROR - Request for asins [] failed`

1. should the code test for key 'products' to avoid the KeyError exception above because it is legitimate case to have no 'products' when exception occurs
2. Can you make the hard-coded max_retry a parameter that can be specified via the API call, and will also be very helpful to make the retry interval be exponentially increasing
3. In the above exception code, why is the asins list empty? There would be no need to call the API if asins list is empty. I stepped through the code, it appears that the code does not consider the fact that self.user.RemainingTokens() could be negative when calculating nrequest. Can this be considered?

Thanks

**Comment by akaszynski** [comment]
Code has been refactored and this is probably not an issue anymore.  Can you recheck on your end and let me know?

**Comment by akaszynski** [comment]
Going to close this issue soon unless I hear back soon.

**Comment by akaszynski** [comment]
Fixed in ``keepa==0.17.1``
