### ISSUE TITLE
Some asins would return error when plotting graph

### ISSUE THREAD

**Issue by chipsslave** [akaszynski/keepa#37]
`asins = ['B01I6KT07E', 'B01G5BJHVK', 'B017LJP1MO']`

above asins return the following error when trying to plot graphs using the below code:

```
products = api.query(asins)
keepa.plot_product(products[0])
```
Any advice?

Error:

```
Traceback (most recent call last):
  File "D:/python_projects/keepa/test.py", line 29, in <module>
    keepa.plot_product(products[0])
  File "D:\python_projects\keepa\venv\lib\site-packages\keepa\plotting.py", line 114, in plot_product
    plt.show(block=True)
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\pyplot.py", line 254, in show
    return _show(*args, **kw)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 25, in __call__
    manager.show(**kwargs)
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 107, in show
    self.canvas.show()
  File "C:\Program Files\JetBrains\PyCharm 2018.3.1\helpers\pycharm_matplotlib_backend\backend_interagg.py", line 62, in show
    self.figure.tight_layout()
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\figure.py", line 2374, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\tight_layout.py", line 366, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\tight_layout.py", line 115, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\tight_layout.py", line 116, in <listcomp>
    if ax.get_visible()])
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\axes\_base.py", line 4373, in get_tightbbox
    bb_xaxis = self.xaxis.get_tightbbox(renderer)
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\axis.py", line 1140, in get_tightbbox
    ticks_to_draw = self._update_ticks(renderer)
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\axis.py", line 1023, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\axis.py", line 967, in iter_ticks
    majorLocs = self.major.locator()
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\dates.py", line 1230, in __call__
    self.refresh()
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\dates.py", line 1250, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "D:\python_projects\keepa\venv\lib\site-packages\matplotlib\dates.py", line 1001, in viewlim_to_dt
    .format(vmin))


ValueError: view limit minimum -0.001 is less than 1 and is an invalid Matplotlib date value. This often happens if you pass a non-datetime value to an axis that has datetime units
```

**Comment by akaszynski** [comment]
Looks like the products contain no data because you're querying with the wrong domain.  Use:
```python
products = api.query(asins, domain='DE')
```

I've added in a check for this in the latest release ``keepa==0.16.3`` that returns a helpful error rather than forwarding empty data to matplotlib.

**Comment by chipsslave** [comment]
Would you be able to suggest if there is a workaround how I could get a domain for asin numbers returned by keepa api as there doesnt seem to be a field determining which domain it belongs to when requesting deals.

**Comment by akaszynski** [comment]
Good question.  Not with the current interface on Python.

I'm afraid I don't know.  You might try asking the question at the [keepa fourms](https://keepa.com/#!discuss/).  I'm afraid I'm just the maintainer for the Python interface to keepa.
